[package]
name = "chen_lang"
version = "0.1.0"
authors = [ "zuisong <378818573@qq.com>" ]
edition = "2018"

[dependencies]
log = "0.4.11"
simple_logger = "1.11.0"
clap = "2.33.3"
quickcheck = "0.9.2"
anyhow = "1.0.37"
