# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  test-cov:
    cmds:
      - cargo tarpaulin --config tarpaulin.toml

  wasm-build:
    desc: Build the WASM package
    cmds:
      - wasm-pack build --target web --out-dir docs/pkg


  wasm-test:
    desc: Run WASM tests
    cmds:
      - wasm-pack test --headless --firefox
